#!/usr/bin/env bash

set -e

curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GITHUB_TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/$GITHUB_REPOSITORY/dependency-graph/sbom > sbom.json

curl -T sbom.json https://sbom.sh
