name: Development

on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - dev.*

jobs:
  pre-setup:
    if: github.actor != 'github-classroom[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Cache python packages'
        id: pip-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('*/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - if: ${{ steps.pip-cache.outputs.cache-hit != 'true' }}
        name: 'Install pip packages'
        continue-on-error: true
        run: make install

      - name: 'Check cache status'
        run: |
          echo "Cache Key: ${{ runner.os }}-pip-${{ hashFiles('*/requirements.txt') }}"
          pip list packages

  linter:
    if: github.actor != 'github-classroom[bot]'
    runs-on: ubuntu-latest
    needs: pre-setup
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup packages'
        run: make install

      - name: 'Code lint'
        run: make lint
      
      - name: 'Upload lint reports'
        uses: actions/upload-artifact@v3
        with:
          name: lints-reports
          path: reports/lint-reports/**

  unit-tests:
    if: github.actor != 'github-classroom[bot]'
    runs-on: ubuntu-latest
    needs: pre-setup
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup packages'
        run: make install

      - name: 'Test code'
        run: make test
      
      - name: 'Upload tests reports'
        uses: actions/upload-artifact@v3
        with:
          name: tests-reports
          path: reports/html/**
